import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
	docsSidebar: [
		'intro',
		{
			type: 'category',
			label: 'CLI Reference',
			link: { type: 'generated-index', title: 'CLI Reference', slug: '/cli' },
			items: [{ type: 'autogenerated', dirName: 'cli' }],
		},
		'roadmap',
		'contributing',
	],
}

export default sidebars
