global:
  scrape_interval: 15s

scrape_configs:
  - job_name: nut
    metrics_path: /nut
    static_configs:
      - targets: ['192.0.2.10']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: nut-exporter:9995
