#!/bin/bash
#
# NUT Server Setup Script
# Installs and configures NUT server on Debian/Ubuntu systems
#
# Usage: sudo ./setup-server.sh [UPS_NAME] [DRIVER]
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
UPS_NAME="${1:-myups}"
DRIVER="${2:-usbhid-ups}"
UPS_DESC="My UPS"
MONITOR_USER="upsmon"
ADMIN_USER="admin"

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    log_error "Cannot detect OS"
    exit 1
fi

log_info "Detected OS: $OS"
log_info "Setting up NUT server..."

# Generate passwords
MONITOR_PASS=$(openssl rand -base64 12 | tr -d '/+=')
ADMIN_PASS=$(openssl rand -base64 12 | tr -d '/+=')
REMOTE_PASS=$(openssl rand -base64 12 | tr -d '/+=')

# Install NUT
log_info "Installing NUT packages..."
case $OS in
    ubuntu|debian)
        apt-get update
        apt-get install -y nut nut-server nut-client
        ;;
    centos|rhel|fedora)
        dnf install -y nut nut-client
        ;;
    *)
        log_error "Unsupported OS: $OS"
        exit 1
        ;;
esac

# Detect UPS
log_info "Detecting UPS devices..."
if command -v lsusb &> /dev/null; then
    lsusb | grep -i ups || log_warn "No UPS detected via USB. Please check connection."
fi

# Auto-detect the driver with nut-scanner now that NUT is installed. The
# inventory-supplied $DRIVER is only a guess (often the usbhid-ups default);
# prefer whatever nut-scanner actually finds on the bus. Falls back to the
# requested driver when nothing is detected (e.g. no USB UPS, or a serial
# unit that -U doesn't cover).
if command -v nut-scanner &> /dev/null; then
    DETECTED_DRIVER=$(nut-scanner -U 2>/dev/null | awk -F'"' '/^[[:space:]]*driver/ {print $2; exit}')
    if [ -n "$DETECTED_DRIVER" ]; then
        if [ "$DETECTED_DRIVER" != "$DRIVER" ]; then
            log_info "nut-scanner detected driver '$DETECTED_DRIVER' (overriding requested '$DRIVER')"
            DRIVER="$DETECTED_DRIVER"
        else
            log_info "nut-scanner confirmed driver '$DRIVER'"
        fi
    else
        log_warn "nut-scanner found no USB UPS; using requested driver '$DRIVER'"
    fi
fi

# Back up any existing NUT config so re-runs don't silently destroy customizations
if compgen -G "/etc/nut/*.conf" > /dev/null; then
    BACKUP_DIR="/etc/nut/backup-$(date +%Y%m%d-%H%M%S)"
    log_info "Backing up existing /etc/nut/*.conf to $BACKUP_DIR"
    mkdir -p "$BACKUP_DIR"
    cp -a /etc/nut/*.conf "$BACKUP_DIR/" 2>/dev/null || true
fi

# Create nut.conf
log_info "Configuring NUT mode..."
cat > /etc/nut/nut.conf << EOF
# NUT Mode Configuration
# netserver = share UPS over network (recommended for homelab)
MODE=netserver
EOF

# Create ups.conf
log_info "Configuring UPS driver..."
cat > /etc/nut/ups.conf << EOF
# UPS Configuration
# Run 'nut-scanner' to auto-detect UPS devices

[$UPS_NAME]
    driver = $DRIVER
    port = auto
    desc = "$UPS_DESC"
    pollinterval = 5
EOF

# Create upsd.conf
log_info "Configuring NUT server..."
cat > /etc/nut/upsd.conf << EOF
# NUT Server Configuration
# Listen on all interfaces for network clients
LISTEN 0.0.0.0 3493
LISTEN 127.0.0.1 3493

# Maximum data age before marking stale
MAXAGE 15
EOF

# Create upsd.users
log_info "Creating NUT users..."
cat > /etc/nut/upsd.users << EOF
# NUT Users Configuration
# Generated by setup script - please change passwords!

# Admin user - for configuration changes
[$ADMIN_USER]
    password = $ADMIN_PASS
    actions = SET
    instcmds = ALL

# Local monitor user
[$MONITOR_USER]
    password = $MONITOR_PASS
    upsmon primary

# Remote client user
[upsmon_remote]
    password = $REMOTE_PASS
    upsmon secondary
EOF

# Create upsmon.conf
log_info "Configuring UPS monitor..."
cat > /etc/nut/upsmon.conf << EOF
# UPS Monitor Configuration

MONITOR $UPS_NAME@localhost 1 $MONITOR_USER $MONITOR_PASS primary

MINSUPPLIES 1
SHUTDOWNCMD "/sbin/shutdown -h +0"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
FINALDELAY 5

# Notifications
NOTIFYFLAG ONLINE SYSLOG+WALL
NOTIFYFLAG ONBATT SYSLOG+WALL
NOTIFYFLAG LOWBATT SYSLOG+WALL
NOTIFYFLAG FSD SYSLOG+WALL
NOTIFYFLAG COMMOK SYSLOG+WALL
NOTIFYFLAG COMMBAD SYSLOG+WALL
NOTIFYFLAG SHUTDOWN SYSLOG+WALL
NOTIFYFLAG REPLBATT SYSLOG+WALL

POWERDOWNFLAG /etc/killpower
EOF

# Fix permissions
log_info "Setting file permissions..."
chown root:nut /etc/nut/*.conf
chmod 640 /etc/nut/*.conf
chmod 640 /etc/nut/upsd.users

# Start services
log_info "Starting NUT services..."

# Stop any previously-running NUT services so they don't keep stale config
systemctl stop nut-monitor 2>/dev/null || true
systemctl stop nut-server 2>/dev/null || true
systemctl stop 'nut-driver@*' 2>/dev/null || true
systemctl stop nut-driver 2>/dev/null || true

systemctl daemon-reload

# NUT 2.8+ (Ubuntu 24.04, Debian 12+) uses instanced nut-driver@<ups>.service
# units managed by nut-driver-enumerator.service. Older NUT uses a single
# nut-driver.service.
if systemctl list-unit-files | grep -q '^nut-driver-enumerator\.service'; then
    log_info "Detected modern NUT (instanced drivers via nut-driver-enumerator)"
    systemctl enable nut-driver-enumerator.service nut-server.service nut-monitor.service
    systemctl restart nut-driver-enumerator.service
else
    log_info "Detected legacy NUT (single nut-driver.service)"
    systemctl enable nut-driver.service nut-server.service nut-monitor.service
    systemctl restart nut-driver.service
fi
sleep 2
systemctl restart nut-server.service
sleep 2
systemctl restart nut-monitor.service

# Test connection
log_info "Testing UPS connection..."
sleep 3
if upsc $UPS_NAME@localhost &>/dev/null; then
    log_info "✓ UPS connection successful!"
    echo ""
    upsc $UPS_NAME@localhost | head -20
else
    log_warn "Could not connect to UPS. Check driver and USB connection."
    log_warn "Run: upsdrvctl -D start  to debug"
fi

# Print credentials
echo ""
echo "=============================================="
echo -e "${GREEN}NUT Server Setup Complete!${NC}"
echo "=============================================="
echo ""
echo "UPS Name: $UPS_NAME"
echo ""
echo "Generated Credentials (SAVE THESE!):"
echo "----------------------------------------------"
echo "Admin User:      $ADMIN_USER"
echo "Admin Password:  $ADMIN_PASS"
echo ""
echo "Monitor User:    $MONITOR_USER"
echo "Monitor Pass:    $MONITOR_PASS"
echo ""
echo "Remote User:     upsmon_remote"
echo "Remote Pass:     $REMOTE_PASS"
echo "----------------------------------------------"
echo ""
echo "Test command:    upsc $UPS_NAME@localhost"
echo "Remote access:   upsc $UPS_NAME@$(hostname -I | awk '{print $1}')"
echo ""
echo "For remote clients, use:"
echo "  Server: $(hostname -I | awk '{print $1}')"
echo "  Port:   3493"
echo "  User:   upsmon_remote"
echo "  Pass:   $REMOTE_PASS"
echo ""

# Save credentials to file
CREDS_FILE="/root/nut-credentials.txt"
cat > $CREDS_FILE << EOF
NUT Server Credentials
Generated: $(date)
======================

Admin User:     $ADMIN_USER
Admin Pass:     $ADMIN_PASS

Monitor User:   $MONITOR_USER
Monitor Pass:   $MONITOR_PASS

Remote User:    upsmon_remote
Remote Pass:    $REMOTE_PASS

Server IP:      $(hostname -I | awk '{print $1}')
Port:           3493
UPS Name:       $UPS_NAME
EOF
chmod 600 $CREDS_FILE
log_info "Credentials saved to $CREDS_FILE"
