// Command gen-docs emits the homelab-nut CLI reference as a tree of
// markdown files under apps/docs/docs/cli/, suitable for consumption by
// Docusaurus's autogenerated sidebar.
//
// Run from the repo root:
//
//	go run ./cmd/gen-docs
//
// or via `make docs-cli`. The generated files are tracked so the docs
// site builds without a Go toolchain — only regenerated when the CLI
// surface changes.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/rtorcato/homelab-nut/internal/cli"
	"github.com/spf13/cobra/doc"
)

const (
	outDir = "apps/docs/docs/cli"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-docs:", err)
		os.Exit(1)
	}
}

func run() error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", outDir, err)
	}

	// We need the same command tree the binary uses. cli.Execute() runs the
	// tree; cli has no exported constructor today, so we build one here that
	// mirrors what Execute does. If the cli API grows a public NewRoot or
	// similar, switch to that.
	root := cli.NewRootForDocs(cli.BuildInfo{Version: "vX.Y.Z"})

	// Strip the cwd from "see also" links and rewrite cross-refs to suit
	// Docusaurus (where slugs live without the .md suffix).
	linkHandler := func(name string) string {
		base := strings.TrimSuffix(name, ".md")
		return "./" + base
	}
	filePrepender := func(filename string) string {
		// Cobra's auto-generated files are missing front-matter; add a tiny
		// header so Docusaurus uses our preferred sidebar order.
		base := filepath.Base(filename)
		title := strings.TrimSuffix(base, ".md")
		title = strings.ReplaceAll(title, "_", " ")
		return fmt.Sprintf("---\ntitle: %s\nslug: /cli/%s\n---\n\n", title, strings.TrimSuffix(base, ".md"))
	}

	if err := doc.GenMarkdownTreeCustom(root, outDir, filePrepender, linkHandler); err != nil {
		return fmt.Errorf("generate markdown: %w", err)
	}

	fmt.Printf("Wrote CLI reference to %s\n", outDir)
	return nil
}
