package inventory

import (
	"fmt"
	"io"
	"os"

	"gopkg.in/yaml.v3"
)

// Save validates inv and writes it to path. The file is written atomically
// (write-to-tempfile, rename) so a partial write can't corrupt the existing
// inventory on disk.
func (inv *Inventory) Save(path string) error {
	if err := inv.Validate(); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(".", ".homelab-nut.yaml.*")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}
	tmpPath := tmp.Name()
	// Best-effort cleanup on any early return.
	defer func() {
		_ = os.Remove(tmpPath)
	}()

	if _, err := io.WriteString(tmp, header()); err != nil {
		tmp.Close()
		return fmt.Errorf("write header: %w", err)
	}
	if err := inv.Render(tmp); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp file: %w", err)
	}

	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("rename %s -> %s: %w", tmpPath, path, err)
	}
	return nil
}

// Render marshals inv as YAML to w. Used by Save and by the init wizard's
// preview-before-confirm step.
//
// Named Render (rather than WriteTo) to avoid clashing with the conventional
// io.WriterTo signature.
func (inv *Inventory) Render(w io.Writer) error {
	enc := yaml.NewEncoder(w)
	enc.SetIndent(2)
	if err := enc.Encode(inv); err != nil {
		return fmt.Errorf("marshal inventory: %w", err)
	}
	return enc.Close()
}

// header is the comment block we prepend to generated inventories. Plain
// strings (not yaml.Node) keep Marshal output uncluttered.
func header() string {
	return `# homelab-nut inventory — generated by ` + "`homelab-nut init`" + `.
#
# Edit with ` + "`homelab-nut inventory edit`" + ` (re-validates on save) or any
# YAML editor. Run ` + "`homelab-nut inventory validate`" + ` to check the
# schema and rules. The schema is documented in ROADMAP.md.

`
}
