#!/usr/bin/env bash
#
# Setup Remote Shutdown via SSH
# Run this on the Pi (NUT server) to:
#   1. Generate an SSH key for root
#   2. Copy it to the remote node (prompts for password once)
#   3. Install the battery-shutdown daemon
#   4. Create and enable a systemd service
#
# Usage: sudo ./setup-remote-shutdown.sh [user@host] [threshold%]
#
# Examples:
#   sudo ./setup-remote-shutdown.sh
#   sudo ./setup-remote-shutdown.sh myuser@control-node
#   sudo ./setup-remote-shutdown.sh myuser@control-node 50
#   sudo ./setup-remote-shutdown.sh "myuser@control-node myuser@node2" 40
#
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
err()  { echo -e "${RED}Error:${NC} $*" >&2; exit 1; }
ok()   { echo -e "${GREEN}✓${NC} $*"; }
info() { echo -e "${CYAN}»${NC} $*"; }
warn() { echo -e "${YELLOW}!${NC} $*"; }

[[ $EUID -ne 0 ]] && err "Run as root: sudo $0 $*"

REMOTE_NODES="${1:-myuser@control-node}"
THRESHOLD="${2:-50}"
CONF="/etc/ups-battery-shutdown.conf"
DAEMON_SRC="$(dirname "$0")/battery-shutdown.sh"
DAEMON_DST="/usr/local/bin/ups-battery-shutdown"
SERVICE="/etc/systemd/system/ups-battery-shutdown.service"
SSH_KEY="/root/.ssh/id_ed25519_ups"

# Auto-detect UPS from local NUT
UPS=$(upsc -l localhost 2>/dev/null | head -n1 || true)
[[ -z "$UPS" ]] && UPS="myups"
UPS="${UPS}@localhost"

echo
echo -e "${CYAN}=== UPS Remote Shutdown Setup ===${NC}"
echo "  Nodes:     $REMOTE_NODES"
echo "  Threshold: ${THRESHOLD}%"
echo "  UPS:       $UPS"
echo

# ── 1. SSH key ──────────────────────────────────────────────────────────────

info "Checking SSH key..."
mkdir -p /root/.ssh
chmod 700 /root/.ssh
if [[ ! -f "$SSH_KEY" ]]; then
    ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -C "ups-battery-shutdown@$(hostname)"
    ok "Generated $SSH_KEY"
else
    ok "SSH key already exists: $SSH_KEY"
fi

# ── 2. Copy key to each remote node ─────────────────────────────────────────

for NODE in $REMOTE_NODES; do
    info "Copying SSH key to $NODE (you will be prompted for the password)..."
    if ssh-copy-id -i "${SSH_KEY}.pub" "$NODE"; then
        ok "Key copied to $NODE"
    else
        echo
        warn "ssh-copy-id failed. You can add the key manually instead."
        warn "On $NODE, append this line to ~/.ssh/authorized_keys:"
        echo
        echo "    $(cat "${SSH_KEY}.pub")"
        echo
        read -r -p "Press Enter once the key is in place..."
    fi
done

# ── 3. Test SSH connection ───────────────────────────────────────────────────

echo
for NODE in $REMOTE_NODES; do
    info "Testing SSH connection to $NODE..."
    SSH_ERR=$(ssh -i "$SSH_KEY" \
        -o StrictHostKeyChecking=no \
        -o ConnectTimeout=10 \
        -o BatchMode=yes \
        "$NODE" 'echo ok' 2>&1) && SSH_OK=1 || SSH_OK=0
    if [[ "$SSH_OK" -eq 1 ]]; then
        ok "SSH to $NODE works"
    else
        echo -e "${RED}SSH test failed:${NC} $SSH_ERR"
        echo
        warn "Troubleshooting tips:"
        echo "  1. Is the host reachable?  ping ${NODE##*@}"
        echo "  2. Is SSH running?         ssh ${NODE} (try manually)"
        echo "  3. Key authorized?         check ~/.ssh/authorized_keys on $NODE"
        echo "  4. Non-standard port?      add -p <port> to SSH_OPTS in $DAEMON_DST"
        err "Fix SSH access to $NODE and re-run this script."
    fi
done

# ── 4. Configure passwordless sudo on remote ─────────────────────────────────

echo
for NODE in $REMOTE_NODES; do
    RUSER="${NODE%%@*}"
    info "Checking sudo shutdown on $NODE..."
    # Test if sudo shutdown -h is already allowed (dry-run with --no-execute)
    if ssh -i "$SSH_KEY" -o BatchMode=yes -o ConnectTimeout=10 \
            "$NODE" 'sudo -n shutdown --help' &>/dev/null; then
        ok "sudo shutdown already works for $RUSER on $NODE"
    else
        warn "sudo shutdown needs to be configured on $NODE."
        warn "Run this on $NODE (or press Enter to skip and do it manually):"
        echo
        echo "    echo '${RUSER} ALL=(ALL) NOPASSWD: /sbin/shutdown' | sudo tee /etc/sudoers.d/ups-shutdown"
        echo
        read -r -p "Press Enter once configured (or to skip)..."
    fi
done

# ── 5. Install daemon script ─────────────────────────────────────────────────

info "Installing daemon script..."
[[ ! -f "$DAEMON_SRC" ]] && err "Cannot find battery-shutdown.sh at $DAEMON_SRC"
install -m 755 "$DAEMON_SRC" "$DAEMON_DST"
ok "Installed $DAEMON_DST"

# ── 6. Write config ──────────────────────────────────────────────────────────

info "Writing config to $CONF..."
cat > "$CONF" << EOF
# UPS Battery Remote Shutdown Configuration
# Generated by setup-remote-shutdown.sh on $(date)

UPS=${UPS}
THRESHOLD=${THRESHOLD}
REMOTE_NODES="${REMOTE_NODES}"
POLL_INTERVAL=30
SSH_KEY=${SSH_KEY}
EOF
chmod 640 "$CONF"
ok "Config written: $CONF"

# ── 7. Patch SSH key into daemon ─────────────────────────────────────────────

# Only patch if not already patched
if ! grep -q "id_ed25519_ups" "$DAEMON_DST"; then
    sed -i "s|SSH_OPTS=\"|SSH_OPTS=\"-i ${SSH_KEY} |" "$DAEMON_DST"
fi

# ── 8. Systemd service ───────────────────────────────────────────────────────

info "Creating systemd service..."
cat > "$SERVICE" << 'UNIT'
[Unit]
Description=UPS Battery Remote Shutdown Watcher
After=nut-server.service nut-monitor.service network.target
Wants=nut-server.service

[Service]
Type=simple
ExecStart=/usr/local/bin/ups-battery-shutdown
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable ups-battery-shutdown.service
systemctl restart ups-battery-shutdown.service
ok "Service enabled and started"

# ── 9. Status summary ────────────────────────────────────────────────────────

echo
STATUS=$(upsc "$UPS" ups.status 2>/dev/null || echo "unknown")
CHARGE=$(upsc "$UPS" battery.charge 2>/dev/null || echo "unknown")

echo -e "${GREEN}=== Setup Complete ===${NC}"
echo
echo "  UPS status:  $STATUS"
echo "  Battery:     ${CHARGE}%"
echo "  Threshold:   ${THRESHOLD}%  (shutdown triggers at or below this)"
echo "  Nodes:       $REMOTE_NODES"
echo
echo "  Monitor logs:   journalctl -u ups-battery-shutdown -f"
echo "  Service status: systemctl status ups-battery-shutdown"
echo "  Dry-run test:   $DAEMON_DST --test"
echo
warn "When battery hits ${THRESHOLD}% on battery, the Pi will SSH to [$REMOTE_NODES] and run 'sudo shutdown -h now'."
echo
