#!/usr/bin/env bash
#
# Setup Remote Shutdown via SSH
# Run this on the Pi (NUT server) to:
#   1. Generate an SSH key for root
#   2. Install the battery-shutdown daemon
#   3. Create and enable a systemd service
#
# Usage: sudo ./setup-remote-shutdown.sh [user@host] [threshold%]
#
# Examples:
#   sudo ./setup-remote-shutdown.sh
#   sudo ./setup-remote-shutdown.sh myuser@control-node
#   sudo ./setup-remote-shutdown.sh myuser@control-node 50
#   sudo ./setup-remote-shutdown.sh "myuser@control-node myuser@node2" 40
#
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
err()  { echo -e "${RED}Error:${NC} $*" >&2; exit 1; }
ok()   { echo -e "${GREEN}✓${NC} $*"; }
info() { echo -e "${CYAN}»${NC} $*"; }
warn() { echo -e "${YELLOW}!${NC} $*"; }

[[ $EUID -ne 0 ]] && err "Run as root: sudo $0 $*"

REMOTE_NODES="${1:-myuser@control-node}"
THRESHOLD="${2:-50}"
CONF="/etc/ups-battery-shutdown.conf"
DAEMON_SRC="$(dirname "$0")/battery-shutdown.sh"
DAEMON_DST="/usr/local/bin/ups-battery-shutdown"
SERVICE="/etc/systemd/system/ups-battery-shutdown.service"
SSH_KEY="/root/.ssh/id_ed25519_ups"

# Auto-detect UPS from local NUT
UPS=$(upsc -l localhost 2>/dev/null | head -n1 || true)
[[ -z "$UPS" ]] && UPS="myups"
UPS="${UPS}@localhost"

echo
echo -e "${CYAN}=== UPS Remote Shutdown Setup ===${NC}"
echo "  Nodes:     $REMOTE_NODES"
echo "  Threshold: ${THRESHOLD}%"
echo "  UPS:       $UPS"
echo

# ── 1. SSH key ──────────────────────────────────────────────────────────────

info "Checking SSH key..."
if [[ ! -f "$SSH_KEY" ]]; then
    ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -C "ups-battery-shutdown@$(hostname)"
    ok "Generated $SSH_KEY"
else
    ok "SSH key already exists: $SSH_KEY"
fi

echo
warn "You must copy the public key to each remote node."
warn "Run the following for each node and enter the password when prompted:"
echo
for NODE in $REMOTE_NODES; do
    echo "    ssh-copy-id -i ${SSH_KEY}.pub ${NODE}"
done
echo
read -r -p "Press Enter once you've copied the key(s), then we'll test the connection..."

# Test SSH to each node
for NODE in $REMOTE_NODES; do
    info "Testing SSH to $NODE..."
    if ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
           -o BatchMode=yes "$NODE" 'echo ok' &>/dev/null; then
        ok "SSH to $NODE works"
    else
        err "Cannot SSH to $NODE. Ensure the key is authorized and the host is reachable."
    fi
done

# ── 2. Verify sudo shutdown works on remote ──────────────────────────────────

echo
warn "The remote user needs passwordless sudo for shutdown."
warn "On each node, run:"
echo
for NODE in $REMOTE_NODES; do
    RUSER="${NODE%%@*}"
    echo "    echo '${RUSER} ALL=(ALL) NOPASSWD: /sbin/shutdown' | sudo tee /etc/sudoers.d/ups-shutdown"
done
echo
read -r -p "Press Enter once sudoers is configured..."

# ── 3. Install daemon script ─────────────────────────────────────────────────

info "Installing daemon script..."
[[ ! -f "$DAEMON_SRC" ]] && err "Cannot find battery-shutdown.sh at $DAEMON_SRC"
install -m 755 "$DAEMON_SRC" "$DAEMON_DST"
ok "Installed $DAEMON_DST"

# ── 4. Write config ──────────────────────────────────────────────────────────

info "Writing config to $CONF..."
cat > "$CONF" << EOF
# UPS Battery Remote Shutdown Configuration
# Generated by setup-remote-shutdown.sh on $(date)

UPS=${UPS}
THRESHOLD=${THRESHOLD}
REMOTE_NODES="${REMOTE_NODES}"
POLL_INTERVAL=30
EOF
chmod 640 "$CONF"
ok "Config written"

# ── 5. Patch SSH key into daemon ─────────────────────────────────────────────
# Append the key path to SSH_OPTS in the installed daemon
sed -i "s|SSH_OPTS=\"|SSH_OPTS=\"-i ${SSH_KEY} |" "$DAEMON_DST"

# ── 6. Systemd service ───────────────────────────────────────────────────────

info "Creating systemd service..."
cat > "$SERVICE" << 'UNIT'
[Unit]
Description=UPS Battery Remote Shutdown Watcher
After=nut-server.service nut-monitor.service network.target
Wants=nut-server.service

[Service]
Type=simple
ExecStart=/usr/local/bin/ups-battery-shutdown
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable ups-battery-shutdown.service
systemctl restart ups-battery-shutdown.service
ok "Service enabled and started"

# ── 7. Dry-run test ──────────────────────────────────────────────────────────

echo
info "Running dry-run test..."
source "$CONF"
STATUS=$(upsc "$UPS" ups.status 2>/dev/null || echo "unknown")
CHARGE=$(upsc "$UPS" battery.charge 2>/dev/null || echo "unknown")
echo "  UPS status:  $STATUS"
echo "  Battery:     ${CHARGE}%"
echo "  Threshold:   ${THRESHOLD}%"
echo

"$DAEMON_DST" --test &
sleep 5
kill %1 2>/dev/null || true

echo
ok "Setup complete!"
echo
echo "  Monitor logs:   journalctl -u ups-battery-shutdown -f"
echo "  Service status: systemctl status ups-battery-shutdown"
echo "  Dry-run test:   $DAEMON_DST --test"
echo
warn "To simulate: disconnect power from the UPS and let the battery drain to ${THRESHOLD}%."
warn "The Pi will SSH to [$REMOTE_NODES] and run 'sudo shutdown -h now'."
echo
