#!/usr/bin/env bash
#
# Non-interactive installer for the homelab-nut battery-shutdown daemon.
# Companion to the homelab-nut Go CLI's `shutdown-daemon` role — wraps
# the same install logic as `scripts/ups-service.sh` but without
# prompting (the role passes everything via env vars).
#
# Required env vars:
#   HOMELAB_NUT_DAEMON_B64   base64-encoded battery-shutdown.sh content
#   UPS                      e.g. myups@localhost
#   THRESHOLD                battery % (1-99)
#   POLL_INTERVAL            seconds (>0)
#   REMOTE_NODES             space-separated user@host list
#
# Optional env vars:
#   REMOTE_SHUTDOWN_CMD      default: ~/shutdown.sh
#   LOG_FILE                 default: /var/log/ups-battery-shutdown/ups-battery-shutdown.log
#   SLACK_WEBHOOK            empty = Slack disabled
#   REMOTE_CMDS_B64          base64 of newline-joined "CMD_<host>=<cmd>" per-target
#                            command overrides; empty = none (all use the default)
#
# Outputs the daemon's SSH public key on stdout so the caller can
# distribute it to each shutdown-target's authorized_keys.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: must run as root (use sudo)" >&2
    exit 1
fi

: "${HOMELAB_NUT_DAEMON_B64:?missing HOMELAB_NUT_DAEMON_B64}"
: "${UPS:?missing UPS}"
: "${THRESHOLD:?missing THRESHOLD}"
: "${POLL_INTERVAL:?missing POLL_INTERVAL}"
: "${REMOTE_NODES:?missing REMOTE_NODES}"

REMOTE_SHUTDOWN_CMD="${REMOTE_SHUTDOWN_CMD:-~/shutdown.sh}"
LOG_FILE="${LOG_FILE:-/var/log/ups-battery-shutdown/ups-battery-shutdown.log}"
SLACK_WEBHOOK="${SLACK_WEBHOOK:-}"

# The daemon installs as root (it writes to /usr/local/bin, /etc, and the
# systemd dir) but runs as this dedicated, login-less system user — a
# network-egress service should never hold root at runtime.
DAEMON_USER="homelab-nut"
DAEMON_HOME="/var/lib/homelab-nut"

DAEMON_DST="/usr/local/bin/ups-battery-shutdown"
CONF_DST="/etc/ups-battery-shutdown.conf"
SERVICE_FILE="/etc/systemd/system/ups-battery-shutdown.service"
SSH_KEY="${DAEMON_HOME}/.ssh/id_ed25519_ups"

log() { echo "[setup-shutdown-daemon] $*" >&2; }

# 0. Create the dedicated, unprivileged service user if it doesn't exist.
if ! id -u "$DAEMON_USER" >/dev/null 2>&1; then
    log "creating system user $DAEMON_USER"
    useradd --system --home-dir "$DAEMON_HOME" --create-home \
        --shell /usr/sbin/nologin "$DAEMON_USER"
fi

# 1. Install the daemon binary (755 so the unprivileged service user can exec it).
log "installing $DAEMON_DST"
mkdir -p "$(dirname "$DAEMON_DST")"
echo "$HOMELAB_NUT_DAEMON_B64" | base64 -d > "$DAEMON_DST"
chmod 755 "$DAEMON_DST"

# 2. Write the config (host-specific values from env).
log "writing $CONF_DST"
cat > "$CONF_DST" <<EOF
# Generated by homelab-nut shutdown-daemon role.
# Edit and re-run \`homelab-nut apply\` to regenerate from inventory.
UPS=${UPS}
THRESHOLD=${THRESHOLD}
POLL_INTERVAL=${POLL_INTERVAL}
REMOTE_NODES="${REMOTE_NODES}"
SSH_KEY=${SSH_KEY}
REMOTE_SHUTDOWN_CMD=${REMOTE_SHUTDOWN_CMD}
LOG_FILE=${LOG_FILE}
EOF
if [[ -n "$SLACK_WEBHOOK" ]]; then
    echo "SLACK_WEBHOOK=${SLACK_WEBHOOK}" >> "$CONF_DST"
fi
# Per-target command overrides (CMD_<host>=cmd). Without these, every node
# falls back to REMOTE_SHUTDOWN_CMD — which breaks targets that need an inline
# command (e.g. UniFi devices that can't host ~/shutdown.sh).
REMOTE_CMDS_B64="${REMOTE_CMDS_B64:-}"
if [[ -n "$REMOTE_CMDS_B64" ]]; then
    DECODED_CMDS="$(echo "$REMOTE_CMDS_B64" | base64 -d)"
    if [[ -n "$DECODED_CMDS" ]]; then
        log "writing per-target command overrides"
        printf '%s\n' "$DECODED_CMDS" >> "$CONF_DST"
    fi
fi
# Group-readable by the service user so it can source the conf (which may hold
# SLACK_WEBHOOK), but not world-readable.
chown "root:${DAEMON_USER}" "$CONF_DST"
chmod 640 "$CONF_DST"

# 3. Generate the daemon's SSH key if missing, owned by the service user.
install -d -m700 -o "$DAEMON_USER" -g "$DAEMON_USER" "$(dirname "$SSH_KEY")"
if [[ ! -f "$SSH_KEY" ]]; then
    log "generating $SSH_KEY"
    ssh-keygen -t ed25519 -N '' -C "homelab-nut shutdown-daemon" -f "$SSH_KEY" >/dev/null
fi
chown "${DAEMON_USER}:${DAEMON_USER}" "$SSH_KEY" "${SSH_KEY}.pub"
chmod 600 "$SSH_KEY"

# 4. Install the systemd unit.
log "writing $SERVICE_FILE"
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Homelab NUT battery-shutdown daemon
After=network-online.target nut-server.service
Wants=network-online.target

[Service]
Type=simple
User=${DAEMON_USER}
Group=${DAEMON_USER}
ExecStart=${DAEMON_DST}
Restart=on-failure
RestartSec=5s
# systemd creates these owned by the service user: /run/ups-battery-shutdown
# (lock file) and /var/log/ups-battery-shutdown (logs).
RuntimeDirectory=ups-battery-shutdown
LogsDirectory=ups-battery-shutdown
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
chmod 644 "$SERVICE_FILE"

# 5. Reload, enable, start.
log "systemctl daemon-reload + enable + restart"
systemctl daemon-reload
systemctl enable ups-battery-shutdown.service >/dev/null
systemctl restart ups-battery-shutdown.service

# 6. Output the public key on stdout so the caller can distribute it.
echo
echo "==== SHUTDOWN DAEMON PUBLIC KEY ===="
cat "${SSH_KEY}.pub"
echo "===================================="
echo
echo "Add the key above to each shutdown-target's ~/.ssh/authorized_keys"
echo "for the user the daemon will SSH in as."
echo "(The daemon runs as the '${DAEMON_USER}' system user; its key lives at ${SSH_KEY}.)"

log "done"
